// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTMUqWOUeB3zOT4GFbF9vq6yOl8WKm4k',
    appId: '1:544383111794:web:d764e8bb274b627eb6a8eb',
    messagingSenderId: '544383111794',
    projectId: 'english-modzy',
    authDomain: 'english-modzy.firebaseapp.com',
    storageBucket: 'english-modzy.firebasestorage.app',
    measurementId: 'G-PDR9JGLBER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_3aacYcZr8WMLrDXbCAyqepI6rUeCic',
    appId: '1:544383111794:android:43ff177fbe6470c1b6a8eb',
    messagingSenderId: '544383111794',
    projectId: 'english-modzy',
    storageBucket: 'english-modzy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuQuWNCvuCC7cCf3Oj3UBsFN0f0gqWIug',
    appId: '1:544383111794:ios:5bce1582cb28a0a4b6a8eb',
    messagingSenderId: '544383111794',
    projectId: 'english-modzy',
    storageBucket: 'english-modzy.firebasestorage.app',
    iosBundleId: 'com.example.modzyEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuQuWNCvuCC7cCf3Oj3UBsFN0f0gqWIug',
    appId: '1:544383111794:ios:5bce1582cb28a0a4b6a8eb',
    messagingSenderId: '544383111794',
    projectId: 'english-modzy',
    storageBucket: 'english-modzy.firebasestorage.app',
    iosBundleId: 'com.example.modzyEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTMUqWOUeB3zOT4GFbF9vq6yOl8WKm4k',
    appId: '1:544383111794:web:de0d7155f2f7e8a4b6a8eb',
    messagingSenderId: '544383111794',
    projectId: 'english-modzy',
    authDomain: 'english-modzy.firebaseapp.com',
    storageBucket: 'english-modzy.firebasestorage.app',
    measurementId: 'G-4JLRHBGW30',
  );
}
